// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package dbengine

import (
	"github.com/google/uuid"
)

type Testfile struct {
	ID       uuid.UUID `json:"id"`
	Filename string    `json:"filename"`
	Contents []byte    `json:"contents"`
	ChunkNum int64     `json:"chunk_num"`
}
